# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-27 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordinatepanel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinator',
            name='address',
        ),
        migrations.RemoveField(
            model_name='coordinator',
            name='city',
        ),
        migrations.RemoveField(
            model_name='coordinator',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='coordinator',
            name='pesel',
        ),
        migrations.RemoveField(
            model_name='coordinator',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='coordinator',
            name='zip_code',
        ),
    ]
