# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-10 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinatepanel', '0002_auto_20181227_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retreatormusictraining',
            name='type',
            field=models.CharField(choices=[('R', 'Rekolekcje'), ('W', 'Warsztaty'), ('M', 'Warsztaty muzyczne')], max_length=1, verbose_name='Typ'),
        ),
    ]
