# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-15 19:42
from __future__ import unicode_literals

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('coordinatepanel', '0003_auto_20190105_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='disabled_sight',
            new_name='bat',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='wheelchair',
            new_name='bear',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='mental_disability',
            new_name='cat',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='not_need_help',
            new_name='dog',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='epilepsy',
            new_name='fish',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='crutches',
            new_name='frog',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='disabled_hands',
            new_name='monkey',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='disabled_hearing',
            new_name='spider',
        ),
        migrations.AlterField(
            model_name='participant',
            name='details',
            field=fernet_fields.fields.EncryptedTextField(blank=True, max_length=200, null=True, verbose_name='Opis'),
        ),
    ]
