# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-11 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinatepanel', '0003_auto_20190210_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='retreatormusictraining',
            name='with_accommodation',
            field=models.BooleanField(default=False, verbose_name='Zapewniony nocleg'),
        ),
    ]
