# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-11 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinatepanel', '0004_retreatormusictraining_with_accommodation'),
    ]

    operations = [
        migrations.AddField(
            model_name='retreatormusictraining',
            name='with_additional_night',
            field=models.BooleanField(default=False, verbose_name='Możliwość dodatkowego noclegu po wydarzeniu'),
        ),
    ]
