# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-18 22:23
from __future__ import unicode_literals

from django.db import migrations, models
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('coordinatepanel', '0004_auto_20190115_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='bat',
            field=models.BooleanField(default=False, verbose_name='Nietoperz'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='bear',
            field=models.BooleanField(default=False, verbose_name='Miś'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='cat',
            field=models.BooleanField(default=False, verbose_name='Kot'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='communication',
            field=models.CharField(choices=[('OK', 'Narcyz'), ('TR', 'Kaktus'), ('KS', 'Fikus'), ('MI', 'Hiacynt'), ('N', 'Róża')], max_length=2, verbose_name='Komunikacja'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='details',
            field=fernet_fields.fields.EncryptedTextField(blank=True, max_length=200, null=True, verbose_name='Inne'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='dog',
            field=models.BooleanField(default=False, verbose_name='Pies'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='fish',
            field=models.BooleanField(default=False, verbose_name='Ryba'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='frog',
            field=models.BooleanField(default=False, verbose_name='Żaba'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='monkey',
            field=models.BooleanField(default=False, verbose_name='Małpka'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='spider',
            field=models.BooleanField(default=False, verbose_name='Pająk'),
        ),
    ]
