# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-03 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinatepanel', '0005_retreatormusictraining_with_additional_night'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='info',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Informacje'),
        ),
    ]
