# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-18 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinatepanel', '0005_auto_20190118_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='details',
            new_name='others',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='communication',
        ),
        migrations.AddField(
            model_name='participant',
            name='flower',
            field=models.CharField(choices=[('OK', 'Narcyz'), ('TR', 'Kaktus'), ('KS', 'Fikus'), ('MI', 'Hiacynt'), ('N', 'Róża')], default='OK', max_length=2, verbose_name='Kwiatek'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participant',
            name='address',
            field=models.CharField(max_length=50, verbose_name='Adres'),
        ),
    ]
