# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-20 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinatepanel', '0006_auto_20190119_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='drugs',
        ),
        migrations.AddField(
            model_name='participant',
            name='candies',
            field=models.CharField(choices=[('T', 'Tak'), ('N', 'Nie'), ('BD', 'Brak danych')], default=1, max_length=2, verbose_name='Czy je słodycze?'),
        ),
    ]
