# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-11 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinatepanel', '0008_auto_20190209_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='retreatormusictraining',
            name='with_accommodation',
            field=models.BooleanField(default=False, verbose_name='Zapewniony nocleg'),
        ),
        migrations.AddField(
            model_name='retreatormusictraining',
            name='with_additional_night',
            field=models.BooleanField(default=False, verbose_name='Możliwość dodatkowego noclegu po wydarzeniu'),
        ),
    ]
