# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-25 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coordinatepanel', '0010_auto_20190303_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipant',
            name='volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coordinatepanel.Volunteer', verbose_name='Wolontariusz'),
        ),
    ]
