# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-25 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinatepanel', '0011_eventparticipant_volunteer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='surname',
            field=models.CharField(max_length=100, verbose_name='Nazwisko'),
        ),
    ]
