# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-04 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinatepanel', '0012_auto_20190325_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchvolunteer',
            name='participant_helper',
            field=models.BooleanField(default=False, verbose_name='Pomoc przy popdopiecznych'),
        ),
    ]
