# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-07-09 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinatepanel', '0013_batchvolunteer_participant_helper'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchparticipant',
            name='payment_id',
            field=models.CharField(default='677911345', max_length=15, verbose_name='ID Płatności'),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='payment_id',
            field=models.CharField(default='847434166', max_length=15, verbose_name='ID Płatności'),
        ),
    ]
