# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-08-14 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('coordinatepanel', '0015_auto_20190710_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchparticipant',
            name='payment_id',
            field=models.CharField(default='#768618404', max_length=15, verbose_name='ID Płatności'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='payment_id',
            field=models.CharField(default='#913343757', max_length=15, verbose_name='ID Płatności'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='others',
            field=fernet_fields.fields.EncryptedTextField(blank=True, max_length=500, null=True, verbose_name='Inne'),
        ),
    ]
