# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-11-26 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coordinatepanel', '0017_auto_20190921_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tytuł')),
                ('content', models.TextField(max_length=10000, verbose_name='Opis')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='gallery', verbose_name='Zdjęcie')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coordinatepanel.Batch', verbose_name='Turnus')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coordinatepanel.Event', verbose_name='Wydarzenie')),
                ('retreat_or_music_training', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coordinatepanel.RetreatOrMusicTraining', verbose_name='Rekolekcje/Warsztaty')),
            ],
            options={
                'verbose_name_plural': 'Posty wydarzeń',
                'verbose_name': 'Post wydarzenia',
            },
        ),
        migrations.AlterField(
            model_name='batchparticipant',
            name='payment_id',
            field=models.CharField(default='#457382445', max_length=15, verbose_name='ID Płatności'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='payment_id',
            field=models.CharField(default='#545165624', max_length=15, verbose_name='ID Płatności'),
        ),
    ]
