# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-11-28 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinatepanel', '0018_auto_20191126_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpost',
            name='begin_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data rozpoczęcia'),
        ),
        migrations.AlterField(
            model_name='batchparticipant',
            name='payment_id',
            field=models.CharField(default='#336635280', max_length=15, verbose_name='ID Płatności'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='payment_id',
            field=models.CharField(default='#562569905', max_length=15, verbose_name='ID Płatności'),
        ),
    ]
