# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-12-17 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinatepanel', '0019_auto_20191128_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='family_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nazwisko rodowe'),
        ),
        migrations.AlterField(
            model_name='batchparticipant',
            name='payment_id',
            field=models.CharField(default='#550343820', max_length=15, verbose_name='ID Płatności'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='payment_id',
            field=models.CharField(default='#559914249', max_length=15, verbose_name='ID Płatności'),
        ),
    ]
