# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-02-03 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinatepanel', '0021_auto_20191222_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Zapisy zamknięte'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Zapisy zamknięte'),
        ),
        migrations.AddField(
            model_name='retreatormusictraining',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Zapisy zamknięte'),
        ),
        migrations.AlterField(
            model_name='batchparticipant',
            name='payment_id',
            field=models.CharField(default='#331648885', max_length=15, verbose_name='ID Płatności'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='payment_id',
            field=models.CharField(default='#274418576', max_length=15, verbose_name='ID Płatności'),
        ),
    ]
