# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-03-07 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinatepanel', '0022_auto_20200203_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventvolunteer',
            name='payment_id',
            field=models.CharField(default='#wy0w0', max_length=15, verbose_name='ID Płatności'),
        ),
        migrations.AddField(
            model_name='retreatormusictrainingperson',
            name='payment_id',
            field=models.CharField(default='#wrwm0i0', max_length=15, verbose_name='ID Płatności'),
        ),
        migrations.AlterField(
            model_name='batchparticipant',
            name='payment_id',
            field=models.CharField(default='#266936474', max_length=15, verbose_name='ID Płatności'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='payment_id',
            field=models.CharField(default='#800388505', max_length=15, verbose_name='ID Płatności'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='how_know_dj',
            field=models.CharField(choices=[('Z', 'Od znajomych wolontariuszy'), ('P', 'Od znajomych podopiecznych'), ('RP', 'Z rekolekcji parafialnych'), ('K', 'Z kościoła'), ('D', 'Ze spotkania w moim duszpasterstwie'), ('AD', 'Z Anielskiej Domówki'), ('US', 'Z uczelni lub ze szkoły'), ('FB', 'Z Facebooka'), ('TV', 'Z radia, TV, prasy'), ('S', 'Z tej strony internetowej'), ('YT', 'Z filmu na YouTube'), ('I', 'Inne')], max_length=2, verbose_name='Skąd zna DJ?'),
        ),
        migrations.AlterField(
            model_name='retreatormusictrainingperson',
            name='how_know_dj',
            field=models.CharField(blank=True, choices=[('Z', 'Od znajomych wolontariuszy'), ('P', 'Od znajomych podopiecznych'), ('RP', 'Z rekolekcji parafialnych'), ('K', 'Z kościoła'), ('D', 'Ze spotkania w moim duszpasterstwie'), ('AD', 'Z Anielskiej Domówki'), ('US', 'Z uczelni lub ze szkoły'), ('FB', 'Z Facebooka'), ('TV', 'Z radia, TV, prasy'), ('S', 'Z tej strony internetowej'), ('YT', 'Z filmu na YouTube'), ('I', 'Inne')], max_length=2, null=True, verbose_name='Skąd znasz DJ?'),
        ),
        migrations.AlterField(
            model_name='retreatormusictrainingperson',
            name='how_know_training',
            field=models.CharField(blank=True, choices=[('Z', 'Od znajomych wolontariuszy'), ('P', 'Od znajomych podopiecznych'), ('RP', 'Z rekolekcji parafialnych'), ('K', 'Z kościoła'), ('D', 'Ze spotkania w moim duszpasterstwie'), ('AD', 'Z Anielskiej Domówki'), ('US', 'Z uczelni lub ze szkoły'), ('FB', 'Z Facebooka'), ('TV', 'Z radia, TV, prasy'), ('S', 'Z tej strony internetowej'), ('YT', 'Z filmu na YouTube'), ('I', 'Inne')], max_length=2, null=True, verbose_name='Skąd dowiedziałeś/aś się o warsztatach?'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='how_know_dj',
            field=models.CharField(choices=[('Z', 'Od znajomych wolontariuszy'), ('P', 'Od znajomych podopiecznych'), ('RP', 'Z rekolekcji parafialnych'), ('K', 'Z kościoła'), ('D', 'Ze spotkania w moim duszpasterstwie'), ('AD', 'Z Anielskiej Domówki'), ('US', 'Z uczelni lub ze szkoły'), ('FB', 'Z Facebooka'), ('TV', 'Z radia, TV, prasy'), ('S', 'Z tej strony internetowej'), ('YT', 'Z filmu na YouTube'), ('I', 'Inne')], max_length=2, verbose_name='Skąd znasz DJ?'),
        ),
    ]
