# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-11-04 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinatepanel', '0023_auto_20200307_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventvolunteer',
            name='was_there',
            field=models.BooleanField(default=False, verbose_name='Wolontariusz pojawił się na wydarzeniu'),
        ),
        migrations.AddField(
            model_name='retreatormusictrainingperson',
            name='was_there',
            field=models.BooleanField(default=False, verbose_name='Osoba pojawiła się na warsztatach lub rekolekcjach'),
        ),
        migrations.AlterField(
            model_name='batchparticipant',
            name='payment_id',
            field=models.CharField(default='#715533311', max_length=15, verbose_name='ID Płatności'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='payment_id',
            field=models.CharField(default='#156286019', max_length=15, verbose_name='ID Płatności'),
        ),
    ]
