# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-07 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinatepanel', '0024_auto_20201104_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchparticipant',
            name='payment_id',
            field=models.CharField(default='#922641918', max_length=15, verbose_name='ID Płatności'),
        ),
        migrations.AlterField(
            model_name='batchvolunteer',
            name='participant_helper',
            field=models.BooleanField(default=True, verbose_name='Pomoc przy popdopiecznych'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='payment_id',
            field=models.CharField(default='#815645177', max_length=15, verbose_name='ID Płatności'),
        ),
    ]
