# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-23 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinatepanel', '0025_auto_20211007_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='k_1',
            field=models.IntegerField(blank=True, default=0, verbose_name='K1'),
        ),
        migrations.AddField(
            model_name='participant',
            name='k_2',
            field=models.IntegerField(blank=True, default=0, verbose_name='K2'),
        ),
        migrations.AddField(
            model_name='participant',
            name='k_3',
            field=models.IntegerField(blank=True, default=0, verbose_name='K3'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='experience',
            field=models.IntegerField(blank=True, default=0, verbose_name='Doświadczenie'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='physical_performance',
            field=models.IntegerField(blank=True, default=0, verbose_name='Wydolność fizyczna'),
        ),
        migrations.AlterField(
            model_name='batchparticipant',
            name='payment_id',
            field=models.CharField(default='#335415918', max_length=15, verbose_name='ID Płatności'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='payment_id',
            field=models.CharField(default='#277633926', max_length=15, verbose_name='ID Płatności'),
        ),
    ]
