# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-23 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinatepanel', '0028_auto_20211024_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchparticipant',
            name='payment_id',
            field=models.CharField(default='#452537926', max_length=15, verbose_name='ID Płatności'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='payment_id',
            field=models.CharField(default='#885965443', max_length=15, verbose_name='ID Płatności'),
        ),
    ]
