# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-23 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinatepanel', '0029_auto_20211024_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchvolunteer',
            name='photographing_agreement',
            field=models.BooleanField(default=True, verbose_name='Zgoda na fotografowanie'),
        ),
        migrations.AlterField(
            model_name='batchparticipant',
            name='payment_id',
            field=models.CharField(default='#550995017', max_length=15, verbose_name='ID Płatności'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='payment_id',
            field=models.CharField(default='#842416700', max_length=15, verbose_name='ID Płatności'),
        ),
    ]
