# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-23 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinatepanel', '0031_auto_20211024_0111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='photographing_agreement',
        ),
        migrations.AlterField(
            model_name='batchparticipant',
            name='payment_id',
            field=models.CharField(default='#922373408', max_length=15, verbose_name='ID Płatności'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='payment_id',
            field=models.CharField(default='#272855270', max_length=15, verbose_name='ID Płatności'),
        ),
    ]
