# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-23 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinatepanel', '0032_auto_20211024_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchparticipant',
            name='payment_id',
            field=models.CharField(default='#796655177', max_length=15, verbose_name='ID Płatności'),
        ),
        migrations.AlterField(
            model_name='batchvolunteer',
            name='photographing_agreement',
            field=models.BooleanField(default=False, verbose_name='Zgoda na fotografowanie'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='payment_id',
            field=models.CharField(default='#169594160', max_length=15, verbose_name='ID Płatności'),
        ),
        migrations.AlterField(
            model_name='eventvolunteer',
            name='photographing_agreement',
            field=models.BooleanField(default=False, verbose_name='Zgoda na fotografowanie'),
        ),
    ]
