# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-24 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinatepanel', '0033_auto_20211024_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='warning',
            field=models.BooleanField(default=False, verbose_name='Przypał'),
        ),
        migrations.AlterField(
            model_name='batchparticipant',
            name='payment_id',
            field=models.CharField(default='#903175747', max_length=15, verbose_name='ID Płatności'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='payment_id',
            field=models.CharField(default='#486242773', max_length=15, verbose_name='ID Płatności'),
        ),
    ]
