version: "2"
services:
  django:
    container_name: django_server
    build:
      context: .
      dockerfile: Dockerfile
    image: drabinajakubowa
    stdin_open: true
    tty: true
    volumes:
      - .:/var/www/drabinajakubowa
    ports:
      - "8000:8000"