# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-03-07 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj', '0003_auto_20190213_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='bank_account',
            field=models.CharField(default='64 1600 1462 1842 6409 5000 0002', max_length=32, verbose_name='Nr rachunku bankowego'),
            preserve_default=False,
        ),
    ]
